import pyautogui

pyautogui.press("win")
pyautogui.sleep(1)
pyautogui.write("google")
pyautogui.sleep(1)
pyautogui.press("ENTER")
pyautogui.sleep(1)
pyautogui.click(701,484)
pyautogui.sleep(1)
pyautogui.write("facebook.com")
pyautogui.sleep(1)
pyautogui.press("ENTER")
pyautogui.sleep(2)
pyautogui.write("paulinho@gmail.com")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.sleep(1)
pyautogui.write("123456")